### PR TITLE
Fix value of the `HtmlSelect` of the `ProgressBar` example

### LINKED ISSUE #147: ProgressBar doc displays "None" intent but "Danger" is selected
@yozhgoor small one if you want

### PR DESCRIPTION
**Pull request by yozhgoor**
Closes #147

### CODE REVIEW

File: yewprint-doc/src/progress_bar/mod.rs [hunk 1]
```diff
@@ -89,7 +89,9 @@ crate::build_example_prop_component! {
                                 (Some(Intent::Warning), "Warning".to_string()),
                                 (Some(Intent::Danger), "Danger".to_string()),
                             ]}
+                            value={self.example_props.intent}
                             onchange={self.update_props(ctx, |props, intent| ExampleProps {
+
```
Comment (cecton) [inline yewprint-doc/src/progress_bar/mod.rs:94]: Putting some spaces so the code can breath? :grin:

**Review by cecton — APPROVED** [review]
